ci: try bash script

diff --git a/.github/workflows/eb-deploy.yml b/.github/workflows/eb-deploy.yml
--- a/.github/workflows/eb-deploy.yml
+++ b/.github/workflows/eb-deploy.yml
@@ -40,62 +40,66 @@ jobs:
       - name: Checkout source code
         uses: actions/checkout@v3
 
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.8"
-          cache: pip
-      - name: install ebcli
-        run: pip install awsebcli
+      - run: ./env.sh ${{ secrets.DOPPLER_TOKEN_STAGE }}
+      - run: ls ./ebextensions
+      - run: cat ./ebextensions/02-env-doppler.config
 
-      - name: Configure AWS credentials from Test account
-        uses: aws-actions/configure-aws-credentials@v1-node16
-        with:
-          role-to-assume: arn:aws:iam::364804350459:role/github-actions
-          aws-region: ${{ inputs.region }}
+      # - name: Setup Python
+      #   uses: actions/setup-python@v4
+      #   with:
+      #     python-version: "3.8"
+      #     cache: pip
+      # - name: install ebcli
+      #   run: pip install awsebcli
 
-      - name: eb environment name
-        run: |
-          ENV_NAME=${{ inputs.application_name }}-${{inputs.environment_name}}-${{inputs.platform}}-${{inputs.tags}}
-          echo "ENV_NAME=${ENV_NAME//./-}" >> $GITHUB_ENV
+      # - name: Configure AWS credentials from Test account
+      #   uses: aws-actions/configure-aws-credentials@v1-node16
+      #   with:
+      #     role-to-assume: arn:aws:iam::364804350459:role/github-actions
+      #     aws-region: ${{ inputs.region }}
 
-      - run: eb --version
-
-      #TODO: setup PROD switch
-      # - name: setup env
-      #   # run: eb setenv DOPPLER_TOKEN=TEST
+      # - name: eb environment name
       #   run: |
-      #     echo 'option_settings:' > .ebextensions/02-env-doppler.config;
-      #     echo '  "aws:elasticbeanstalk:application:environment":' >> .ebextensions/02-env-doppler.config;
-      #     echo '    HISTIGNORE: DOPPLER_TOKEN*' >> .ebextensions/02-env-doppler.config;
-      #     echo '    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_STAGE }} ' >> .ebextensions/02-env-doppler.config;
-      #     echo 'commands:' >> .ebextensions/02-env-doppler.config;
-      #     echo '  01-install-doppler:' >> .ebextensions/02-env-doppler.config;
-      #     echo '    command: (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sudo sh ' >> .ebextensions/02-env-doppler.config;
-      # - run: cat .ebextensions/02-env-doppler.config;
+      #     ENV_NAME=${{ inputs.application_name }}-${{inputs.environment_name}}-${{inputs.platform}}-${{inputs.tags}}
+      #     echo "ENV_NAME=${ENV_NAME//./-}" >> $GITHUB_ENV
 
-      - name: eb init
-        #   uses: hmanzur/actions-aws-eb@v1.0.0
-        run: eb init ${{ inputs.application_name }} --region ${{ inputs.region }} --platform ${{ inputs.platform }}
+      # - run: eb --version
 
-      # # search for environment name (matches terminated environments until they're fully removed after ~1hr)
-      # # if the env already exists, then it will output 0 for success or 1 for failure
-      # # on failure - run the create env step
-      # # ensure intermediate steps pass on failed grep: https://stackoverflow.com/questions/73066461/github-actions-why-an-intermediate-command-failure-in-shell-script-would-cause
-      - name: eb describe-environment (aws)
-        id: describe
-        run: |
-          aws elasticbeanstalk describe-environments --environment-name ${{ env.ENV_NAME }} \
-          | grep '"EnvironmentName": "${{ env.ENV_NAME }}"' \
-          || echo "describe=$?" >> $GITHUB_OUTPUT \
-          && exit 0
+      # #TODO: setup PROD switch
+      # # - name: setup env
+      # #   # run: eb setenv DOPPLER_TOKEN=TEST
+      # #   run: |
+      # #     echo 'option_settings:' > .ebextensions/02-env-doppler.config;
+      # #     echo '  "aws:elasticbeanstalk:application:environment":' >> .ebextensions/02-env-doppler.config;
+      # #     echo '    HISTIGNORE: DOPPLER_TOKEN*' >> .ebextensions/02-env-doppler.config;
+      # #     echo '    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_STAGE }} ' >> .ebextensions/02-env-doppler.config;
+      # #     echo 'commands:' >> .ebextensions/02-env-doppler.config;
+      # #     echo '  01-install-doppler:' >> .ebextensions/02-env-doppler.config;
+      # #     echo '    command: (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sudo sh ' >> .ebextensions/02-env-doppler.config;
+      # # - run: cat .ebextensions/02-env-doppler.config;
 
-      - name: eb create environment
-        if: ${{ steps.describe.outputs.describe == 1 }}
-        run: eb create ${{ env.ENV_NAME }} --region ${{ inputs.region }} --platform ${{ inputs.platform }} --verbose
+      # - name: eb init
+      #   #   uses: hmanzur/actions-aws-eb@v1.0.0
+      #   run: eb init ${{ inputs.application_name }} --region ${{ inputs.region }} --platform ${{ inputs.platform }}
 
-      - name: eb deploy
-        run: eb deploy ${{ env.ENV_NAME }} --region ${{ inputs.region }} --message ${{ github.ref }} --process --verbose
+      # # # search for environment name (matches terminated environments until they're fully removed after ~1hr)
+      # # # if the env already exists, then it will output 0 for success or 1 for failure
+      # # # on failure - run the create env step
+      # # # ensure intermediate steps pass on failed grep: https://stackoverflow.com/questions/73066461/github-actions-why-an-intermediate-command-failure-in-shell-script-would-cause
+      # - name: eb describe-environment (aws)
+      #   id: describe
+      #   run: |
+      #     aws elasticbeanstalk describe-environments --environment-name ${{ env.ENV_NAME }} \
+      #     | grep '"EnvironmentName": "${{ env.ENV_NAME }}"' \
+      #     || echo "describe=$?" >> $GITHUB_OUTPUT \
+      #     && exit 0
+
+      # - name: eb create environment
+      #   if: ${{ steps.describe.outputs.describe == 1 }}
+      #   run: eb create ${{ env.ENV_NAME }} --region ${{ inputs.region }} --platform ${{ inputs.platform }} --verbose
+
+      # - name: eb deploy
+      #   run: eb deploy ${{ env.ENV_NAME }} --region ${{ inputs.region }} --message ${{ github.ref }} --process --verbose
 
       # - name: eb create environment
       #   if: ${{ steps.describe.outputs.describe == 1 }}
