ci: compose workflows

diff --git a/.github/workflows/eb-deploy.yml b/.github/workflows/eb-deploy.yml
--- a/.github/workflows/eb-deploy.yml
+++ b/.github/workflows/eb-deploy.yml
@@ -4,20 +4,23 @@ on:
       application_name:
         required: true
         type: string
-      # solution_stack_name:
-      #   description: aws list-available-solution-stacks
-      #   default: 64bit Amazon Linux 2 v3.4.2 running Python 3.8
-      #   type: string
+      solution_stack_name:
+        description: aws list-available-solution-stacks
+        default: 64bit Amazon Linux 2 v3.4.2 running Python 3.8
+        type: string
       region:
         description: AWS region to deploy to
         default: us-east-2
         type: string
       environment_name:
         default: staging
+        #TODO: add this to frontend
+        # required: true
         type: string
       platform:
         default: python-3.8 # eb platform list --region us-east-2
         type: string
+
 jobs:
   deploy:
     name: Deploy to AWS Elastic Beanstalk
@@ -37,9 +40,15 @@ jobs:
           role-to-assume: arn:aws:iam::364804350459:role/github-actions
           aws-region: ${{ inputs.region }}
 
+      - name: Cache Docker images.
+        uses: ScribeMD/docker-cache@0.2.6
+        with:
+          #TODO: change this if different aws-eb docker version used
+          key: docker-${{ runner.os }}-actions-aws-eb@v1.0.0
+
       - name: eb environment name
         run: |
-          ENV_NAME=${{inputs.application_name}}-${{inputs.environment_name}}-${{inputs.platform}}
+          ENV_NAME=${{inputs.environment_name}}-${{inputs.platform}}
           echo "ENV_NAME=${ENV_NAME//./-}" >> $GITHUB_ENV
 
       - name: eb init
@@ -50,17 +59,30 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
 
+        # search for environment name (matches terminated environments until they're fully removed after ~1hr)
+        # if the env already exists, then it will output 0 for success or 1 for failure
+        # on failure - run the create env step
       - name: eb describe-environment (aws)
+        id: describe
         run: |
-          aws elasticbeanstalk describe-environments \
-          --environment-name ${{env.ENV_NAME }}\
-          | grep '"EnvironmentName": "${{ env.ENV_NAME }}"';
+          DESCRIBE=$(aws elasticbeanstalk describe-environments \
+          --environment-name ${{env.ENV_NAME }}); \
+          echo $DESCRIBE | grep '"EnvironmentName": "${{ env.ENV_NAME }}"'; \
+          echo "describe=$?" >> $GITHUB_OUTPUT;
 
+        # run: >
+        #   aws elasticbeanstalk describe-environments \
+        #   --environment-name ${{env.ENV_NAME }}\
+        #   | grep '"EnvironmentName": "${{ env.ENV_NAME }}"');
+        #   echo "DESCRIBE=$?" >> $GITHUB_OUTPUT;
+
+      # - run: echo ${{ steps.describe.outputs.describe }}
       - name: eb create environment
+        if: ${{ steps.describe.outputs.describe == 1 }}
         uses: hmanzur/actions-aws-eb@v1.0.0
-        if: ${{ failure() }} # previous step failed
+        #   # if: ${{ failure() }} # previous step failed
         with:
-          command: "create ${{ env.ENV_NAME }} --region ${{ inputs.region }} --platform ${{ inputs.platform }}"
+          command: "create ${{ env.ENV_NAME }} --region ${{ inputs.region }} --platform ${{ inputs.platform }} --single"
         env:
           AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
